/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package provatc2;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tibd8
 */
public class Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPagInicial = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        menuConsulta = new javax.swing.JMenu();

        jLabel1.setText("Produto:");

        jButton1.setText("Pesquisar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        menuPagInicial.setText("Pagina Inicial");
        menuPagInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPagInicialMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPagInicial);

        menuCadastro.setText("Cadastro de produto");
        menuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastroMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCadastro);

        menuConsulta.setText("Consulta de produto");
        menuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConsultaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel modelotabela = (DefaultTableModel) jTable1.getModel();
        modelotabela.setColumnCount(3);
        modelotabela.setRowCount(0);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Descrição");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Preço");
        Dados d = new Dados();
        if(d.conectar("localhost", "loja", "root", "")) {
            ResultSet rs;
            if(jTextField1.getText().equals("")) {
                rs = d.consultar("select * from produtos");
            } else {
                rs = d.consultar("select * from produtos where descricao = '" 
                                                + jTextField1.getText() + "'");
            }
            int linha = 0;
            try {
                while(rs.next()) {
                    modelotabela.addRow(new  String[modelotabela.getColumnCount()]);
                    modelotabela.setValueAt(rs.getString("codigo"), linha, 0);
                    modelotabela.setValueAt(rs.getString("descricao"), linha, 1);
                    modelotabela.setValueAt(rs.getString("valor"), linha, 2);
                    linha++;
                }
            } catch (Exception e) {
                System.err.println("Erro: " + e);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void menuPagInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPagInicialMouseClicked
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuPagInicialMouseClicked

    private void menuCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastroMouseClicked
        cadastro c = new cadastro();
        c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroMouseClicked

    private void menuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultaMouseClicked
        Pesquisa p = new Pesquisa();
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuPagInicial;
    // End of variables declaration//GEN-END:variables
}
