/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package provatc2;

/**
 *
 * @author tibd8
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPagInicial = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        menuConsulta = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provatc2/Imagem/logotipo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);

        menuPagInicial.setText("Pagina Inicial");
        menuPagInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPagInicialMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPagInicial);

        menuCadastro.setText("Cadastro de produto");
        menuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastroMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCadastro);

        menuConsulta.setText("Consulta de produto");
        menuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConsultaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConsulta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadastroMouseClicked
        cadastro c = new cadastro();
        c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroMouseClicked

    private void menuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConsultaMouseClicked
        Pesquisa p = new Pesquisa();
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultaMouseClicked

    private void menuPagInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPagInicialMouseClicked
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuPagInicialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuPagInicial;
    // End of variables declaration//GEN-END:variables
}
